#!/usr/bin/env python


import os
import webapp2
import jinja2

from google.appengine.ext import db


#Jinja2 Directory Configuration
template_dir = os.path.join(os.path.dirname(__file__), 'templates')
jinja_env = jinja2.Environment(loader = jinja2.FileSystemLoader(template_dir),
                               autoescape = True)


#Default Handler
class Handler(webapp2.RequestHandler):
    def get(self):
        users = db.GqlQuery('SELECT * FROM User')
        self.render('index.html',users = users)

    def write(self, *a, **kw):
        self.response.out.write(*a, **kw)

    def render_str(self, template, **params):
        t = jinja_env.get_template(template)
        return t.render(params)

    def render(self, template, **kw):
        self.write(self.render_str(template, **kw))


class User(db.Model):
    name = db.StringProperty( required = True )
    cpf = db.StringProperty(required = True)
	fone = db.StringProperty(required = True)
    end = db.StringProperty(required = True)

class Filme(db.Model):
	nome = db.StringProperty(required = True)
	diretor = db.StringProperty (required = True)
	lancamento = db.StringProperty (required = True)
	codigo = db.StringProperty (required = True)
	
class CadastroFilmeHandler(Handler):
	def get(self):
		self.render('cadastrofilme.html')
		
		def post(self):
    
		nome = self.request.get('nome')
		diretor = self.request.get('diretor')
		lancamento = self.request.get('lancamento')
		codigo = self.request.get('codigo')

    
		if nome and diretor and lancamento and codigo:
            filme = Filme(titulo = titulo, autor = autor, editora = editora, codigo = codigo)
            filme.put()
			self.redirect( '/cadastrofilme' )
				

        else:
            self.response.out.write( 'Erro: Ocorreu um erro no cadastro do filme!' )


class CadastroClienteHandler(Handler):
    def get(self):
        self.render('cadastrocliente.html')

        def post(self):
        name = self.request.get('name')
        cpf = self.request.get('cpf')
        fone = self.request.get('fone')
        end = self.request.get('end')


        if name and cpf and fone and end:
            user = User(name = name, cpf = cpf, fone = fone, end = end)
            user.put()
            self.redirect( '/cadastrocliente' )
                

        else:
            self.response.out.write( 'Erro: Ocorreu um erro no cadastro do usuario!' )

	
class MainHandler(Handler):

    def get(self):
        self.render('index.html')
    

class ConsultaHandler(Handler):

    def get(self):
        self.render('consulta.html')



    
app = webapp2.WSGIApplication([
    ('/', MainHandler)
	('/cadastrocliente', CadastroClienteHandler)
    ('/cadastrofilme', CadastroFilmeHandler)
    ('/consulta', ConsultaHandler)
], debug=True)


